### ISSUE TITLE
write function to read the wavenumber

### ISSUE THREAD

**Issue by ThomasKnecht** [spectral-cockpit/opusreader2#2]
apparently a separate function for reading the wavenumber is needed.

**Comment by philipp-baumann** [comment]
yes. its basically linear interpolation from FXV (first x-variable) and LXV (last x-variable).

**Comment by philipp-baumann** [comment]
done by @ThomasKnecht 
see https://github.com/spectral-cockpit/opusreader2/blob/main/R/calculate_wavenumber.R
