### ISSUE TITLE
🏗 Name first level of list returned by `read_opus()` with string containing file name (DSN)

### ISSUE THREAD

**Issue by philipp-baumann** [spectral-cockpit/opusreader2#51]

**Comment by philipp-baumann** [comment]
cc @laura-summerauer

**Comment by philipp-baumann** [comment]
Hey @laura-summerauer , the feature is ready to be tested :)

**Comment by laura-summerauer** [comment]
Wonderful! :) Thanks!

**Comment by philipp-baumann** [comment]
Hey @laura-summerauer and @ThomasKnecht , after some thoughts and discussions, we can now simplify the naming. So this means the PR for the naming condiders just DSN base file names.

For more sophisticated filtering with basic metadata, e.g., time stamps, I'll make a separate issue and corresponding PR 😎 this way the development stays focused.
