### ISSUE TITLE
Add basic metadata for straight-forward data filters

### ISSUE THREAD

**Issue by philipp-baumann** [spectral-cockpit/opusreader2#84]
OPUS files contain key metadata such as timestamps or sample information, which are pivotal for managing spectral databases and modeling downstream.
This provides opportunity for adding basic metadata in an extra list element. We would call this list element appended to "opusreader2" class `basic_metadata`. This basic metadata includes the column entries [WIP]
- `dsn_filename`
- `dsn_path`
- `opus_filename`
- `opus_path`
- `timestamp_string`
- `local_datetime`
- `local_timezone`
- `utc_time_posixct`

cc @ThomasKnecht

**Comment by philipp-baumann** [comment]
implemented in #85

**Comment by philipp-baumann** [comment]
implemented in #85

**Comment by davidbenncsiro** [comment]
I'll be doing more with this library again soon. Thanks @philipp-baumann.

**Comment by philipp-baumann** [comment]
👍 let me now if you have any feedback
